/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/explore/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet values, counts and numeric ranges for the explore filters */
        get: operations["list_facets_api_v1_explore_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explore/genes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filter, sort and page the IEI gene set, with facet counts */
        get: operations["list_genes_api_v1_explore_genes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and component state */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/job-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job kinds this deployment can run */
        get: operations["list_job_kinds_api_v1_job_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs of the calling workspace, newest first */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Start a computational job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One job with stages, result and artifacts */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a job artifact */
        get: operations["get_artifact_api_v1_jobs__job_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Follow a job (Server-Sent Events) */
        get: operations["follow_job_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job events as JSON */
        get: operations["get_job_log_api_v1_jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Immutable run manifest */
        get: operations["get_manifest_api_v1_jobs__job_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset, sources and deployment features */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model providers, capabilities and availability */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One model provider */
        get: operations["get_model_api_v1_models__provider_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorRef */
        ActorRef: {
            /** Actor Id */
            actor_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anonymous" | "account" | "system";
        };
        /** ArtifactOut */
        ArtifactOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            role: components["schemas"]["ArtifactRole"];
            /** Sample Index */
            sample_index: number | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            structure_origin: components["schemas"]["StructureOrigin"] | null;
            /**
             * Url
             * @description API path of the file; prefix with the API origin
             */
            url: string;
        };
        /**
         * ArtifactRole
         * @enum {string}
         */
        ArtifactRole: "structure" | "confidence_summary" | "pae" | "pde" | "plddt" | "affinity" | "msa" | "model_input" | "source_response" | "log" | "manifest" | "other";
        /** Authoring */
        Authoring: {
            /**
             * Method
             * @enum {string}
             */
            method: "human" | "llm_assisted";
            /**
             * Model
             * @default null
             */
            model: string | null;
        };
        /** Availability */
        Availability: {
            /** Available */
            available: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Reason
             * @description Human-readable: why the provider can or cannot run here
             */
            reason: string;
        };
        /** CatalogCounts */
        CatalogCounts: {
            /**
             * Categories
             * @default 0
             */
            categories: number;
            /**
             * Diseases
             * @default 0
             */
            diseases: number;
            /**
             * Flagship Genes
             * @default 0
             */
            flagship_genes: number;
            /**
             * Genes
             * @default 0
             */
            genes: number;
            /**
             * Genes With Uniprot
             * @default 0
             */
            genes_with_uniprot: number;
            /**
             * Subcategories
             * @default 0
             */
            subcategories: number;
        };
        /**
         * CatalogState
         * @enum {string}
         */
        CatalogState: "ready" | "missing" | "generating" | "invalid";
        /** CatalogStatus */
        CatalogStatus: {
            counts: components["schemas"]["CatalogCounts"];
            /** Dataset */
            dataset: string | null;
            /** File Modified At */
            file_modified_at: string | null;
            /** Generated At */
            generated_at: string | null;
            /** Loaded At */
            loaded_at: string | null;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Problems */
            problems: string[];
            /**
             * Skipped Records
             * @default 0
             */
            skipped_records: number;
            state: components["schemas"]["CatalogState"];
        };
        /** Citation */
        Citation: {
            /** Doi */
            doi: string | null;
            /** Pmcid */
            pmcid: string | null;
            /** Pmid */
            pmid: string | null;
            /** Text */
            text: string | null;
            /** Title */
            title: string | null;
            /** Url */
            url: string | null;
            /** Year */
            year: number | null;
        };
        /**
         * ClaimLabel
         * @description Four-label view used by comparison and mechanism stages.
         * @enum {string}
         */
        ClaimLabel: "known_experimentally" | "database_annotation" | "computational_prediction" | "orphafold_hypothesis";
        /** ConfidenceSummary */
        ConfidenceSummary: {
            /**
             * Iptm
             * @description Null for single-chain structures
             * @default null
             */
            iptm: number | null;
            /**
             * Pae Available
             * @default false
             */
            pae_available: boolean;
            /**
             * Pae Max
             * @description Cap of the PAE matrix in angstroms
             * @default null
             */
            pae_max: number | null;
            /** @default null */
            plddt_fractions: components["schemas"]["PlddtFractions"] | null;
            /**
             * Plddt Mean
             * @description Normalised to 0-100
             * @default null
             */
            plddt_mean: number | null;
            /**
             * Plddt Native Scale
             * @default null
             */
            plddt_native_scale: ("0-1" | "0-100") | null;
            /**
             * Provider Native
             * @description Raw provider values, verbatim
             */
            provider_native: {
                [key: string]: unknown;
            };
            /**
             * Ptm
             * @default null
             */
            ptm: number | null;
            /**
             * Ranking Score
             * @default null
             */
            ranking_score: number | null;
            /**
             * Ranking Score Name
             * @default null
             */
            ranking_score_name: string | null;
        };
        /** DatasetInfo */
        DatasetInfo: {
            /** Citation */
            citation: string | null;
            /** @description Counts stated in the seed manifest */
            declared_counts: components["schemas"]["SeedCounts"];
            /** Doi */
            doi: string | null;
            /** Generated At */
            generated_at: string | null;
            /** Id */
            id: string | null;
            /** @description Counts of records actually loaded */
            loaded_counts: components["schemas"]["CatalogCounts"];
        };
        /** DatasetVersion */
        DatasetVersion: {
            /**
             * License
             * @default null
             */
            license: string | null;
            /** Name */
            name: string;
            /**
             * Retrieved At
             * @default null
             */
            retrieved_at: string | null;
            /**
             * Url
             * @default null
             */
            url: string | null;
            /** Version */
            version: string;
        };
        /** EcoRef */
        EcoRef: {
            /**
             * Assigned By
             * @enum {string}
             */
            assigned_by: "source" | "orphafold_mapping";
            /** Id */
            id: string;
            /**
             * Label
             * @default null
             */
            label: string | null;
        };
        /**
         * EntityRef
         * @description Pointer to an entity: URL-facing ID plus the canonical database CURIE where one exists.
         */
        EntityRef: {
            /**
             * Curie
             * @description Canonical database ID, e.g. hgnc:1133
             */
            curie: string | null;
            /**
             * Href
             * @description Web route, when the entity has a page
             */
            href: string | null;
            /**
             * Id
             * @description URL-facing ID: HGNC symbol, UniProt accession, disease slug, variant ID
             */
            id: string;
            /** Label */
            label: string | null;
            type: components["schemas"]["EntityType"];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "disease" | "disease_category" | "gene" | "transcript" | "protein" | "variant" | "residue" | "domain" | "interaction" | "phenotype" | "pathway" | "structure" | "compound" | "drug" | "binding_site" | "target" | "publication" | "job" | "hypothesis" | "project";
        /** EnumEntry */
        EnumEntry: {
            /** Code */
            code: string;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * Evidence
         * @description One attributable scientific statement.
         */
        Evidence: {
            /**
             * Asserted At
             * @default null
             */
            asserted_at: string | null;
            /** @default null */
            authoring: components["schemas"]["Authoring"] | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            readonly claim_label: components["schemas"]["ClaimLabel"];
            /** Code */
            readonly code: string;
            /**
             * @default {
             *       "actor_id": "system",
             *       "kind": "system"
             *     }
             */
            created_by: components["schemas"]["ActorRef"];
            /**
             * Derived From
             * @description Evidence or job IDs
             */
            derived_from: string[];
            /** @default supports */
            direction: components["schemas"]["EvidenceDirection"];
            /** @default null */
            eco: components["schemas"]["EcoRef"] | null;
            evidence_class: components["schemas"]["EvidenceClass"];
            /**
             * Generated By
             * @description Job ID for OrphaFold computations
             * @default null
             */
            generated_by: string | null;
            /** Id */
            id: string;
            /** Label */
            readonly label: string;
            /**
             * Modifiers
             * @description e.g. manual, auto, text_mining
             */
            modifiers: string[];
            /** @default null */
            object: components["schemas"]["EvidenceObject"] | null;
            /**
             * Predicate
             * @default null
             */
            predicate: string | null;
            /** @default null */
            source: components["schemas"]["SourceRecord"] | null;
            /**
             * Statement
             * @description The claim in the source's own words
             * @default null
             */
            statement: string | null;
            /** @default null */
            strength: components["schemas"]["EvidenceStrength"] | null;
            /** @default null */
            structure_origin: components["schemas"]["StructureOrigin"] | null;
            /** @default null */
            subject: components["schemas"]["EntityRef"] | null;
            /**
             * Supersedes
             * @default null
             */
            supersedes: string | null;
        };
        /**
         * EvidenceClass
         * @enum {string}
         */
        EvidenceClass: "experimental" | "clinical_database" | "literature" | "curated_database" | "computational_prediction" | "orphafold_hypothesis";
        /**
         * EvidenceDirection
         * @enum {string}
         */
        EvidenceDirection: "supports" | "disputes" | "neutral";
        /** EvidenceObject */
        EvidenceObject: {
            /** Context */
            context: {
                [key: string]: unknown;
            }[];
            /**
             * Id
             * @default null
             */
            id: string | null;
            /**
             * Label
             * @default null
             */
            label: string | null;
            /** Type */
            type: string;
            /**
             * Unit
             * @default null
             */
            unit: string | null;
            /**
             * Value
             * @default null
             */
            value: string | number | boolean | null;
        };
        /**
         * EvidenceStrength
         * @description Source-native strength. Never merged across schemes.
         */
        EvidenceStrength: {
            /** Criteria */
            criteria: string[];
            /**
             * Max Rank
             * @default null
             */
            max_rank: number | null;
            /**
             * Rank
             * @description Order inside this scheme only
             * @default null
             */
            rank: number | null;
            /**
             * Scheme
             * @description e.g. clinvar_review_status, uniprot_eco, plddt, pdb_resolution
             */
            scheme: string;
            /**
             * Unit
             * @default null
             */
            unit: string | null;
            /**
             * Value
             * @default null
             */
            value: string | number | null;
        };
        /**
         * ExecutionMode
         * @enum {string}
         */
        ExecutionMode: "retrieval" | "remote_api" | "local_cli" | "gpu_worker";
        /** ExploreDisease */
        ExploreDisease: {
            /** Category Id */
            category_id: string | null;
            /** Id */
            id: string;
            /** Inheritance Codes */
            inheritance_codes: string[];
            /**
             * Is Phenocopy
             * @default false
             */
            is_phenocopy: boolean;
            /** Name */
            name: string;
            /** Subcategory Id */
            subcategory_id: string | null;
        };
        /**
         * ExploreFacets
         * @description Counts per facet value, each computed with every other active filter applied.
         */
        ExploreFacets: {
            /** Category */
            category: components["schemas"]["FacetValue"][];
            /** Inheritance */
            inheritance: components["schemas"]["FacetValue"][];
            /** Protein Family */
            protein_family: components["schemas"]["FacetValue"][];
            /** Structure */
            structure: components["schemas"]["FacetValue"][];
            /** Subcategory */
            subcategory: components["schemas"]["FacetValue"][];
        };
        /** ExploreFacetsResponse */
        ExploreFacetsResponse: {
            catalog_state: components["schemas"]["CatalogState"];
            facets: components["schemas"]["ExploreFacets"];
            ranges: components["schemas"]["ExploreRanges"];
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
            /**
             * Total
             * @description Genes matching the active filters
             */
            total: number;
        };
        /** ExploreGene */
        ExploreGene: {
            /** Category Ids */
            category_ids: string[];
            /** Chromosome */
            chromosome: string | null;
            /** Diseases */
            diseases: components["schemas"]["ExploreDisease"][];
            /** Hgnc Id */
            hgnc_id: string | null;
            /** Href */
            href: string;
            /** Inheritance Codes */
            inheritance_codes: string[];
            /**
             * Is Flagship
             * @default false
             */
            is_flagship: boolean;
            /** Name */
            name: string | null;
            /** Protein Family */
            protein_family: string | null;
            /** Protein Length */
            protein_length: number | null;
            /** Protein Name */
            protein_name: string | null;
            stats: components["schemas"]["ExploreGeneStats"];
            /** Subcategory Ids */
            subcategory_ids: string[];
            /** Symbol */
            symbol: string;
            /** Uniprot Accession */
            uniprot_accession: string | null;
        };
        /**
         * ExploreGeneStats
         * @description Source-native counts. Null means the source had no value.
         */
        ExploreGeneStats: {
            /** Clinvar Pathogenic Count */
            clinvar_pathogenic_count: number | null;
            /** Clinvar Total Count */
            clinvar_total_count: number | null;
            /** Experimental Structure Count */
            experimental_structure_count: number | null;
            /** Has Alphafold Model */
            has_alphafold_model: boolean | null;
            /** Publication Count */
            publication_count: number | null;
            /** Retrieved At */
            retrieved_at: string | null;
        };
        /** ExploreGenesResponse */
        ExploreGenesResponse: {
            catalog_state: components["schemas"]["CatalogState"];
            facets: components["schemas"]["ExploreFacets"];
            /** Has More */
            readonly has_more: boolean;
            /** Items */
            items: components["schemas"]["ExploreGene"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            order: components["schemas"]["SortOrder"];
            ranges: components["schemas"]["ExploreRanges"];
            sort: components["schemas"]["ExploreSort"];
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
            /** Total */
            total: number;
        };
        /** ExploreRanges */
        ExploreRanges: {
            pathogenic_variants: components["schemas"]["NumericRange"];
            publications: components["schemas"]["NumericRange"];
            total_variants: components["schemas"]["NumericRange"];
        };
        /**
         * ExploreSort
         * @enum {string}
         */
        ExploreSort: "relevance" | "symbol" | "name" | "pathogenic_variants" | "total_variants" | "publications" | "experimental_structures" | "protein_length";
        /** FacetValue */
        FacetValue: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Parent */
            parent: string | null;
            /** Table */
            table: number | null;
            /** Value */
            value: string;
        };
        /** Features */
        Features: {
            /** Artifact Store */
            artifact_store: string;
            /** Assistant Configured */
            assistant_configured: boolean;
            /** Boltz Configured */
            boltz_configured: boolean;
            /** Database */
            database: string;
            /** Job Queue */
            job_queue: string;
            /** Msa Server Configured */
            msa_server_configured: boolean;
            /** Ncbi Api Key Configured */
            ncbi_api_key_configured: boolean;
            /** Noncommercial Sources Enabled */
            noncommercial_sources_enabled: boolean;
        };
        /** FieldProblem */
        FieldProblem: {
            /** Location */
            location: (string | number)[];
            /** Message */
            message: string;
            /** Type */
            type?: string | null;
        };
        /** Hardware */
        Hardware: {
            /**
             * Accelerator
             * @default null
             */
            accelerator: ("gpu" | "cpu" | "mps") | null;
            /**
             * Gpu Count
             * @default null
             */
            gpu_count: number | null;
            /**
             * Gpu Model
             * @default null
             */
            gpu_model: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            catalog: components["schemas"]["CatalogState"];
            /**
             * Data Release
             * @description Seeded dataset ID and build date, e.g. iuis_2024 2026-10-03
             */
            data_release: string | null;
            /** Database */
            database: string;
            /** Job Queue */
            job_queue: string;
            /**
             * Load Errors
             * @description Plugin modules that failed to import
             */
            load_errors: {
                [key: string]: string;
            };
            /**
             * Status
             * @description ok, or degraded when the database is unreachable
             */
            status: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Version */
            version: string;
            /** Worker */
            worker: string;
        };
        /** JobCreate */
        JobCreate: {
            /**
             * Kind
             * @description A registered job kind; see GET /api/v1/job-kinds
             */
            kind: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Parent Job Id
             * @description Job this run repeats or corrects
             */
            parent_job_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /** JobEventOut */
        JobEventOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Job Id */
            job_id: string;
            /** Level */
            level: string | null;
            /** Message */
            message: string | null;
            /** Stage Id */
            stage_id: string | null;
            /** Type */
            type: string;
        };
        /** JobKindOut */
        JobKindOut: {
            /** Description */
            description: string | null;
            /** Kind */
            kind: string;
            /** Params Schema */
            params_schema: {
                [key: string]: unknown;
            };
            /** Providers */
            providers: string[];
            /** Restartable */
            restartable: boolean;
            /**
             * Result Schema
             * @description JSON Schema of JobOut.result
             */
            result_schema: {
                [key: string]: unknown;
            } | null;
            /** Title */
            title: string;
        };
        /** JobOut */
        JobOut: {
            /** Actor Id */
            actor_id: string | null;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactOut"][];
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Stage */
            current_stage: string | null;
            error: components["schemas"]["JobError"] | null;
            /** Events Url */
            events_url: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Manifest Sha256 */
            manifest_sha256: string | null;
            /** Manifest Url */
            manifest_url: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Parent Job Id */
            parent_job_id: string | null;
            /** Project Id */
            project_id: string | null;
            /** Provider Id */
            provider_id: string | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Stages */
            stages: components["schemas"]["JobStage"][];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            subject: components["schemas"]["EntityRef"] | null;
            /** Title */
            title: string | null;
        };
        /** JobStage */
        JobStage: {
            /** Completed At */
            completed_at: string | null;
            /** Detail */
            detail: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            progress: components["schemas"]["StageProgress"] | null;
            /** Started At */
            started_at: string | null;
            /** @default pending */
            status: components["schemas"]["StageStatus"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** ManifestArtifact */
        ManifestArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Media Type */
            media_type: string;
            /** Path */
            path: string;
            role: components["schemas"]["ArtifactRole"];
            /**
             * Sample Index
             * @default null
             */
            sample_index: number | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** @default null */
            structure_origin: components["schemas"]["StructureOrigin"] | null;
        };
        /** ManifestConfidence */
        ManifestConfidence: {
            /**
             * Ranking Metric
             * @default null
             */
            ranking_metric: string | null;
            /** Samples */
            samples: components["schemas"]["ManifestConfidenceSample"][];
        };
        /** ManifestConfidenceSample */
        ManifestConfidenceSample: {
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Sample Index */
            sample_index: number;
            /**
             * Structure Artifact Id
             * @default null
             */
            structure_artifact_id: string | null;
        };
        /** ManifestExecution */
        ManifestExecution: {
            /**
             * Argv
             * @default null
             */
            argv: string[] | null;
            /**
             * Attempts
             * @default 1
             */
            attempts: number;
            /**
             * Error
             * @default null
             */
            error: {
                [key: string]: unknown;
            } | null;
            /**
             * Exit Code
             * @default null
             */
            exit_code: number | null;
            /**
             * Parent Job Id
             * @default null
             */
            parent_job_id: string | null;
            /** Stages */
            stages: components["schemas"]["ManifestStage"][];
            /**
             * Wall Time Seconds
             * @default null
             */
            wall_time_seconds: number | null;
            /**
             * Worker Id
             * @default null
             */
            worker_id: string | null;
        };
        /** ManifestInputStructure */
        ManifestInputStructure: {
            origin: components["schemas"]["StructureOrigin"];
            /** Sha256 */
            sha256: string;
            source: components["schemas"]["RecordRef"];
        };
        /** ManifestInputs */
        ManifestInputs: {
            /** Database Identifiers */
            database_identifiers: string[];
            /** Ligands */
            ligands: components["schemas"]["ManifestLigand"][];
            /** Sequences */
            sequences: components["schemas"]["ManifestSequence"][];
            /** Structures */
            structures: components["schemas"]["ManifestInputStructure"][];
            /** Variants */
            variants: components["schemas"]["ManifestVariant"][];
        };
        /** ManifestIntegrity */
        ManifestIntegrity: {
            /**
             * Canonicalization
             * @default RFC8785
             * @constant
             */
            canonicalization: "RFC8785";
            /** Manifest Sha256 */
            manifest_sha256: string;
        };
        /** ManifestLigand */
        ManifestLigand: {
            /**
             * Ccd
             * @default null
             */
            ccd: string | null;
            /** Entity Id */
            entity_id: string;
            /**
             * Inchikey
             * @default null
             */
            inchikey: string | null;
            /**
             * Smiles
             * @default null
             */
            smiles: string | null;
            /** Xrefs */
            xrefs: string[];
        };
        /** ManifestMsa */
        ManifestMsa: {
            /** Artifact Ids */
            artifact_ids: string[];
            /** Databases */
            databases: components["schemas"]["DatasetVersion"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "server" | "precomputed" | "single_sequence" | "not_applicable";
            /**
             * Pairing Strategy
             * @default null
             */
            pairing_strategy: string | null;
            /** @default null */
            search_tool: components["schemas"]["SoftwareItem"] | null;
            /**
             * Server Url
             * @default null
             */
            server_url: string | null;
        };
        /** ManifestOutputs */
        ManifestOutputs: {
            /** Artifacts */
            artifacts: components["schemas"]["ManifestArtifact"][];
            confidence: components["schemas"]["ManifestConfidence"];
        };
        /** ManifestProject */
        ManifestProject: {
            /** Project Id */
            project_id: string;
            /**
             * Snapshot Id
             * @default null
             */
            snapshot_id: string | null;
        };
        /** ManifestSequence */
        ManifestSequence: {
            /** Applied Variant Ids */
            applied_variant_ids: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * Is Variant Sequence
             * @default false
             */
            is_variant_sequence: boolean;
            /** Length */
            length: number;
            /** Md5 */
            md5: string;
            /**
             * Molecule Type
             * @default protein
             * @enum {string}
             */
            molecule_type: "protein" | "dna" | "rna";
            /** Refget */
            refget: string;
            /** Sequence */
            sequence: string;
            /** Sha256 */
            sha256: string;
            /** @default null */
            source: components["schemas"]["RecordRef"] | null;
            /**
             * Uniprot Start
             * @default null
             */
            uniprot_start: number | null;
        };
        /** ManifestSoftware */
        ManifestSoftware: {
            /**
             * Container
             * @default null
             */
            container: {
                [key: string]: string;
            } | null;
            /**
             * Cuda
             * @default null
             */
            cuda: string | null;
            /** @default null */
            hardware: components["schemas"]["Hardware"] | null;
            orphafold: components["schemas"]["OrphaFoldSoftware"];
            /** Os */
            os: string;
            /** Packages */
            packages: components["schemas"]["SoftwareItem"][];
            /** Python */
            python: string;
        };
        /** ManifestStage */
        ManifestStage: {
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ManifestVariant */
        ManifestVariant: {
            /** Hgvs */
            hgvs: {
                [key: string]: string;
            };
            /** @default null */
            protein_change: components["schemas"]["ProteinChange"] | null;
            /**
             * Transcript
             * @default null
             */
            transcript: string | null;
            /**
             * Transcript Status
             * @default null
             */
            transcript_status: ("MANE_Select" | "MANE_Plus_Clinical" | "other") | null;
            /** Variant Id */
            variant_id: string;
            /**
             * Vrs Id
             * @default null
             */
            vrs_id: string | null;
            /**
             * Vrs Version
             * @default null
             */
            vrs_version: string | null;
            /** Xrefs */
            xrefs: string[];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Api Prefix */
            api_prefix: string;
            catalog: components["schemas"]["CatalogStatus"];
            dataset: components["schemas"]["DatasetInfo"];
            /** Evidence Classes */
            evidence_classes: components["schemas"]["EnumEntry"][];
            features: components["schemas"]["Features"];
            /** Job Kinds */
            job_kinds: string[];
            /** License */
            license: string;
            /**
             * Live Sources
             * @description Source adapters and whether each is enabled
             */
            live_sources: components["schemas"]["SourceStatus"][];
            /** Name */
            name: string;
            /** Providers */
            providers: string[];
            /** Research Use Notice */
            research_use_notice: string;
            /**
             * Seed Sources
             * @description Release, license and checksum of each seeded source
             */
            seed_sources: components["schemas"]["SeedSource"][];
            /** Structure Origins */
            structure_origins: components["schemas"]["EnumEntry"][];
            /** Version */
            version: string;
        };
        /** ModelCode */
        ModelCode: {
            /**
             * Package
             * @default null
             */
            package: string | null;
            /**
             * Repository
             * @default null
             */
            repository: string | null;
            /**
             * Revision
             * @default null
             */
            revision: string | null;
        };
        /**
         * ModelIdentity
         * @description What exactly produced an output: recorded verbatim in the run manifest.
         */
        ModelIdentity: {
            /** @default null */
            code: components["schemas"]["ModelCode"] | null;
            execution_mode: components["schemas"]["ExecutionMode"];
            /** License */
            license: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Version */
            version: string;
            /** Weights */
            weights: components["schemas"]["ModelWeights"][];
        };
        /** ModelWeights */
        ModelWeights: {
            /** Name */
            name: string;
            /**
             * Revision
             * @default null
             */
            revision: string | null;
            /**
             * Sha256
             * @default null
             */
            sha256: string | null;
            /**
             * Size Bytes
             * @default null
             */
            size_bytes: number | null;
            /**
             * Uri
             * @default null
             */
            uri: string | null;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
        };
        /**
         * NumericRange
         * @description Bounds over the whole catalog, for range controls. Null when no gene has a value.
         */
        NumericRange: {
            /**
             * Known
             * @description Genes for which the source reported a value
             */
            known: number;
            /** Max */
            max: number | null;
            /** Min */
            min: number | null;
        };
        /** OrphaFoldSoftware */
        OrphaFoldSoftware: {
            /**
             * Git Commit
             * @default null
             */
            git_commit: string | null;
            /** Version */
            version: string;
        };
        /** Page[JobOut] */
        Page_JobOut_: {
            /** Has More */
            readonly has_more: boolean;
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PlddtFractions
         * @description Share of residues per pLDDT band (0 to 1).
         */
        PlddtFractions: {
            /** Confident */
            confident: number;
            /** Low */
            low: number;
            /** Very High */
            very_high: number;
            /** Very Low */
            very_low: number;
        };
        /**
         * ProblemDetail
         * @description Body of every error response.
         */
        ProblemDetail: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldProblem"][] | null;
            /** Instance */
            instance?: string | null;
            /** Source */
            source?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** ProteinChange */
        ProteinChange: {
            /** Alt */
            alt: string;
            /** Position */
            position: number;
            /** Ref */
            ref: string;
        };
        /**
         * Provenance
         * @description Envelope recorded on every upstream fetch.
         */
        Provenance: {
            /**
             * Attribution
             * @default null
             */
            attribution: string | null;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /**
             * License
             * @default null
             */
            license: string | null;
            /**
             * License Url
             * @default null
             */
            license_url: string | null;
            /**
             * Method
             * @default GET
             */
            method: string;
            /**
             * Record Id
             * @default null
             */
            record_id: string | null;
            /**
             * Record Url
             * @description Human-facing page of the record
             * @default null
             */
            record_url: string | null;
            /**
             * Release
             * @description Source release; null when the source reports none
             * @default null
             */
            release: string | null;
            /**
             * Request Url
             * @description Request URL with secrets removed
             */
            request_url: string;
            /**
             * Response Sha256
             * @default null
             */
            response_sha256: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Source
             * @description Source adapter ID, e.g. uniprot
             */
            source: string;
            /** Source Name */
            source_name: string;
            /**
             * Stale
             * @description Served past its TTL because the source did not answer
             * @default false
             */
            stale: boolean;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Attribution */
            attribution: string | null;
            availability: components["schemas"]["Availability"];
            /** Capabilities */
            capabilities: string[];
            /** Citation */
            citation: components["schemas"]["Citation"][];
            /**
             * Commercial Use
             * @description Whether the license permits commercial use
             */
            commercial_use: boolean | null;
            execution_mode: components["schemas"]["ExecutionMode"];
            /** Homepage */
            homepage: string | null;
            /** Id */
            id: string;
            /**
             * Job Kinds
             * @description Job kinds that run this provider
             */
            job_kinds: string[];
            kind: components["schemas"]["ProviderKind"];
            /** License */
            license: string | null;
            /** License Url */
            license_url: string | null;
            /** Limitations */
            limitations: string[];
            /** Max Residues */
            max_residues: number | null;
            /** Model Name */
            model_name: string | null;
            /**
             * Model Version
             * @description Null when not known on this deployment
             */
            model_version: string | null;
            /** Name */
            name: string;
            /**
             * Performs Inference
             * @description False for retrieval of an existing prediction
             */
            performs_inference: boolean;
            /**
             * Requires Api Key
             * @default false
             */
            requires_api_key: boolean;
            /**
             * Requires Gpu
             * @default false
             */
            requires_gpu: boolean;
            /** @description Origin carried by structures this provider returns */
            structure_origin: components["schemas"]["StructureOrigin"] | null;
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "structure_predictor" | "binding_predictor" | "variant_effect" | "pocket" | "literature";
        /** RecordRef */
        RecordRef: {
            /** Database */
            database: string;
            /** Record Id */
            record_id: string;
            /**
             * Record Version
             * @default null
             */
            record_version: string | null;
            /**
             * Release
             * @default null
             */
            release: string | null;
            /**
             * Url
             * @default null
             */
            url: string | null;
        };
        /**
         * ResidueRange
         * @description Inclusive range in UniProt canonical numbering.
         */
        ResidueRange: {
            /**
             * Chain
             * @default null
             */
            chain: string | null;
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /** RunManifest */
        RunManifest: {
            actor: components["schemas"]["ActorRef"];
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            execution: components["schemas"]["ManifestExecution"];
            inputs: components["schemas"]["ManifestInputs"];
            integrity: components["schemas"]["ManifestIntegrity"];
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /**
             * Manifest Version
             * @default 1.0.0
             * @constant
             */
            manifest_version: "1.0.0";
            model: components["schemas"]["ModelIdentity"] | null;
            msa: components["schemas"]["ManifestMsa"];
            outputs: components["schemas"]["ManifestOutputs"];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** @default null */
            project: components["schemas"]["ManifestProject"] | null;
            /**
             * Request
             * @description Job parameters exactly as submitted and validated
             */
            request: {
                [key: string]: unknown;
            };
            /**
             * Research Use Only
             * @default true
             * @constant
             */
            research_use_only: true;
            software: components["schemas"]["ManifestSoftware"];
            /** Source Datasets */
            source_datasets: components["schemas"]["DatasetVersion"][];
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /** SeedCounts */
        SeedCounts: {
            /** Categories */
            categories: number | null;
            /** Diseases */
            diseases: number | null;
            /** Entries */
            entries: number | null;
            /** Genes */
            genes: number | null;
            /** Genes With Uniprot */
            genes_with_uniprot: number | null;
        };
        /** SeedSource */
        SeedSource: {
            /** Id */
            id: string;
            /** License */
            license: string | null;
            /** Name */
            name: string | null;
            /** Release */
            release: string | null;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Sha256 */
            sha256: string | null;
            /** Url */
            url: string | null;
        };
        /** SoftwareItem */
        SoftwareItem: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * SortOrder
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /** SourceRecord */
        SourceRecord: {
            /** Database */
            database: string;
            /**
             * License
             * @default null
             */
            license: string | null;
            /** Record Id */
            record_id: string;
            /**
             * Record Version
             * @default null
             */
            record_version: string | null;
            /**
             * Release
             * @default null
             */
            release: string | null;
            /**
             * Request
             * @default null
             */
            request: string | null;
            /**
             * Response Sha256
             * @default null
             */
            response_sha256: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Url
             * @default null
             */
            url: string | null;
        };
        /**
         * SourceState
         * @enum {string}
         */
        SourceState: "ok" | "empty" | "unavailable" | "disabled_by_license" | "not_configured";
        /**
         * SourceStatus
         * @description One row per upstream source consulted for a response.
         */
        SourceStatus: {
            /** Elapsed Ms */
            elapsed_ms: number | null;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /** License */
            license: string | null;
            /** Message */
            message: string | null;
            /** Name */
            name: string;
            /** Release */
            release: string | null;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Source */
            source: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            state: components["schemas"]["SourceState"];
            /** Url */
            url: string | null;
        };
        /**
         * StageProgress
         * @description Measured progress inside a stage. Present only when the work reports real counts.
         */
        StageProgress: {
            /** Completed */
            completed: number;
            /** Total */
            total: number | null;
            /** Unit */
            unit: string | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "pending" | "running" | "done" | "failed" | "skipped" | "cancelled";
        /**
         * StructureAvailability
         * @enum {string}
         */
        StructureAvailability: "experimental" | "predicted" | "none" | "unknown";
        /** StructureCoverage */
        StructureCoverage: {
            /**
             * Covered Residues
             * @default null
             */
            covered_residues: number | null;
            /**
             * Fraction
             * @default null
             */
            fraction: number | null;
            /** Ranges */
            ranges: components["schemas"]["ResidueRange"][];
            /**
             * Sequence Length
             * @default null
             */
            sequence_length: number | null;
            /**
             * Uniprot Accession
             * @default null
             */
            uniprot_accession: string | null;
        };
        /**
         * StructureDescriptor
         * @description A structure of any origin. The origin is always present and always shown.
         */
        StructureDescriptor: {
            /**
             * Attribution
             * @default null
             */
            attribution: string | null;
            /** @default null */
            confidence: components["schemas"]["ConfidenceSummary"] | null;
            /** @default null */
            coverage: components["schemas"]["StructureCoverage"] | null;
            /**
             * Created Date
             * @description Deposition, model creation or inference date
             * @default null
             */
            created_date: string | null;
            files: components["schemas"]["StructureFiles"];
            /**
             * Id
             * @description pdb:<ID>, afdb:<entryId> or of:<job_id>
             */
            id: string;
            /**
             * Job Id
             * @default null
             */
            job_id: string | null;
            /**
             * License
             * @default null
             */
            license: string | null;
            /** Limitations */
            limitations: string[];
            /**
             * Method
             * @description Experimental method, or the tool that predicted it
             * @default null
             */
            method: string | null;
            /**
             * Model Name
             * @default null
             */
            model_name: string | null;
            /**
             * Model Version
             * @default null
             */
            model_version: string | null;
            origin: components["schemas"]["StructureOrigin"];
            /** Origin Label */
            readonly origin_label: string;
            /** @default null */
            provenance: components["schemas"]["Provenance"] | null;
            /**
             * Provider
             * @description Database or model provider ID, e.g. rcsb_pdb, afdb, boltz2
             */
            provider: string;
            /**
             * Provider Name
             * @default null
             */
            provider_name: string | null;
            /**
             * Resolution
             * @description Angstroms; experimental structures only
             * @default null
             */
            resolution: number | null;
            /**
             * Retrieved At
             * @default null
             */
            retrieved_at: string | null;
            /**
             * Source Id
             * @default null
             */
            source_id: string | null;
            /**
             * Source Url
             * @default null
             */
            source_url: string | null;
            /** Tag */
            readonly tag: string;
            /**
             * Title
             * @default null
             */
            title: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** StructureFiles */
        StructureFiles: {
            /**
             * Bcif Url
             * @default null
             */
            bcif_url: string | null;
            /**
             * Cif Url
             * @default null
             */
            cif_url: string | null;
            /**
             * Pae Image Url
             * @default null
             */
            pae_image_url: string | null;
            /**
             * Pae Url
             * @default null
             */
            pae_url: string | null;
            /**
             * Pdb Url
             * @default null
             */
            pdb_url: string | null;
            /**
             * Plddt Url
             * @default null
             */
            plddt_url: string | null;
        };
        /**
         * StructureJobResult
         * @description Result of every job kind that ends with a structure (JobOut.result).
         */
        StructureJobResult: {
            /**
             * Gene Symbol
             * @default null
             */
            gene_symbol: string | null;
            /**
             * Performs Inference
             * @description False when the structure was retrieved, not predicted
             */
            performs_inference: boolean;
            /** @description File URLs point at this job's stored artifacts */
            structure: components["schemas"]["StructureDescriptor"];
            /**
             * @description Where a retrieved model's files live at the source
             * @default null
             */
            upstream_files: components["schemas"]["StructureFiles"] | null;
            /**
             * Variant Id
             * @default null
             */
            variant_id: string | null;
        };
        /**
         * StructureOrigin
         * @description Three structure classes that are never presented as equivalent.
         * @enum {string}
         */
        StructureOrigin: "experimental" | "predicted_external" | "predicted_orphafold";
        /**
         * VariantMetric
         * @enum {string}
         */
        VariantMetric: "pathogenic" | "total";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_facets_api_v1_explore_facets_get: {
        parameters: {
            query?: {
                /** @description IUIS category ID, e.g. iuis-t1. Repeatable */
                category?: string[] | null;
                /** @description IUIS subcategory ID. Repeatable */
                subcategory?: string[] | null;
                /** @description Inheritance code, e.g. AR, AD, XL. Repeatable */
                inheritance?: string[] | null;
                /** @description Text in the gene symbol, gene or protein name, or disease name */
                q?: string | null;
                /** @description Protein family, exact. 'unknown' selects genes with none. Repeatable */
                protein_family?: string[] | null;
                /** @description Structure availability: experimental, predicted, none, unknown. Repeatable */
                structure?: components["schemas"]["StructureAvailability"][] | null;
                /** @description Which ClinVar count the variant range applies to */
                variant_metric?: components["schemas"]["VariantMetric"];
                /** @description Minimum number of reported variants */
                variants_min?: number | null;
                /** @description Maximum number of reported variants */
                variants_max?: number | null;
                /** @description Minimum publication count */
                publications_min?: number | null;
                /** @description Maximum publication count */
                publications_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreFacetsResponse"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_genes_api_v1_explore_genes_get: {
        parameters: {
            query?: {
                /** @description Default: relevance with q, otherwise symbol */
                sort?: components["schemas"]["ExploreSort"] | null;
                /** @description Genes with no value for the sort key come last */
                order?: components["schemas"]["SortOrder"] | null;
                /** @description IUIS category ID, e.g. iuis-t1. Repeatable */
                category?: string[] | null;
                /** @description IUIS subcategory ID. Repeatable */
                subcategory?: string[] | null;
                /** @description Inheritance code, e.g. AR, AD, XL. Repeatable */
                inheritance?: string[] | null;
                /** @description Text in the gene symbol, gene or protein name, or disease name */
                q?: string | null;
                /** @description Protein family, exact. 'unknown' selects genes with none. Repeatable */
                protein_family?: string[] | null;
                /** @description Structure availability: experimental, predicted, none, unknown. Repeatable */
                structure?: components["schemas"]["StructureAvailability"][] | null;
                /** @description Which ClinVar count the variant range applies to */
                variant_metric?: components["schemas"]["VariantMetric"];
                /** @description Minimum number of reported variants */
                variants_min?: number | null;
                /** @description Maximum number of reported variants */
                variants_max?: number | null;
                /** @description Minimum publication count */
                publications_min?: number | null;
                /** @description Maximum publication count */
                publications_max?: number | null;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreGenesResponse"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_job_kinds_api_v1_job_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobKindOut"][];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                /** @description Repeatable */
                status?: components["schemas"]["JobStatus"][] | null;
                kind?: string | null;
                /** @description Entity type the job is about, e.g. protein */
                subject_type?: string | null;
                /** @description Entity ID the job is about, e.g. Q06187 */
                subject_id?: string | null;
                project_id?: string | null;
                /** @description Page size */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: {
                /** @description Anonymous workspace ID generated by the client: 16-128 characters of A-Z a-z 0-9 _ - */
                "X-OrphaFold-Workspace"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobOut_"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous workspace ID generated by the client: 16-128 characters of A-Z a-z 0-9 _ - */
                "X-OrphaFold-Workspace"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description An identical job is already queued or running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_artifact_api_v1_jobs__job_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/octet-stream": unknown;
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous workspace ID generated by the client: 16-128 characters of A-Z a-z 0-9 _ - */
                "X-OrphaFold-Workspace"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    follow_job_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: {
                /** @description Resume after this event ID */
                after?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description status, stage, log and artifact events, then end */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_job_log_api_v1_jobs__job_id__log_get: {
        parameters: {
            query?: {
                /** @description Return events with an ID greater than this */
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventOut"][];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_manifest_api_v1_jobs__job_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run manifest (see docs/ARCHITECTURE.md) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_model_api_v1_models__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"];
                };
            };
            /** @description Problem JSON */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Problem JSON */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
