"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import check_record_consistency as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def check_record_consistency() -> str:
    """Report how evidence, hypotheses and test results are linked, and what is uncited, duplicated or unlinked.
    """
    return _implementation()
