"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import get_interactions as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def get_interactions(accession: str) -> str:
    """Curated protein-protein interactions of a protein from IntAct, strongest first.

    Args:
        accession: UniProt accession.
    """
    return _implementation(accession=accession)
