"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.discovery import get_candidate_detail as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def get_candidate_detail(candidate_ref: str) -> str:
    """The full chain of one candidate: every bridge step with the records it cites, the direction check and the caveats.

    Args:
        candidate_ref: The candidate_ref of a candidate list_candidate_targets returned.
    """
    return _implementation(candidate_ref=candidate_ref)
