"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.candidates import propose_candidates as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def propose_candidates(candidate_refs: list[str], why: str) -> str:
    """Put candidates forward for the safety review. Nothing is recorded as a candidate until the review clears it.

    Args:
        candidate_refs: candidate_ref values from list_candidate_targets, strongest bridge first.
        why: Why these candidates and not the others, in molecular terms.
    """
    return _implementation(candidate_refs=candidate_refs, why=why)
