"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.candidates import record_candidate as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_candidate(candidate_ref: str, what_would_have_to_be_true: str) -> str:
    """Record one candidate the safety review cleared. Target, molecule, bridge, direction check and evidence are attached from the retrieved response.

    Args:
        candidate_ref: candidate_ref of a cleared candidate.
        what_would_have_to_be_true: One plain sentence naming the assumption the whole chain rests on, the
            thing that would have to hold for this candidate to be worth testing. No treatment wording, no
            molecule name other than the candidate's own.
    """
    return _implementation(candidate_ref=candidate_ref, what_would_have_to_be_true=what_would_have_to_be_true)
