"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.candidates import record_candidate_review as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_candidate_review(verdict: str, findings: str) -> str:
    """Record the safety review of the candidate proposal. Every candidate whose direction check is not "matches" is rejected here, with its reason.

    Args:
        verdict: cleared when the proposal may proceed for the candidates whose direction matches,
            blocked when no candidate of the proposal may be recorded at all.
        findings: What was checked: the direction of the mechanism, each molecule's action, the wording of
            the proposal, and which candidates are rejected and why.
    """
    return _implementation(verdict=verdict, findings=findings)
