"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import record_gap as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_gap(statement: str, why_it_matters: str, refs: list[str] | None = None) -> str:
    """Record something the evidence does not answer.

    Args:
        statement: What is unknown or was not found, in one sentence.
        why_it_matters: Why this gap matters for choosing between mechanisms.
        refs: IDs of related record items.
    """
    return _implementation(statement=statement, why_it_matters=why_it_matters, refs=refs)
