"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.candidates import record_target_rationale as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_target_rationale(what_to_act_on: str, why: str) -> str:
    """Record what a drug could act on for the favoured mechanism. The direction rule is attached from the retrieved response.

    Args:
        what_to_act_on: In molecular terms, which protein or node a molecule could act on and in which
            direction (reduce or restore activity). No treatment or dosing wording.
        why: Why the favoured mechanism and its direction lead to that action, naming the hypothesis ID.
    """
    return _implementation(what_to_act_on=what_to_act_on, why=why)
