"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import record_decision as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_decision(favoured_after: str, why: str) -> str:
    """Record the updated decision: which hypothesis is favoured now. The previously favoured one is filled in from the record.

    Args:
        favoured_after: ID (H...) of the hypothesis favoured after the result.
        why: How the measured result leads to this choice, citing the test ID and evidence IDs.
    """
    return _implementation(favoured_after=favoured_after, why=why)
