"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.experiments import run_structure_comparison as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def run_structure_comparison(test_id: str) -> str:
    """Start the reference versus variant structure prediction job of the chosen plan and wait for its result. Needs an approved human decision.

    Args:
        test_id: ID (T...) of the chosen test candidate of kind structure_comparison.
    """
    return _implementation(test_id=test_id)
