"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.experiments import run_stability_test as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def run_stability_test(test_id: str) -> str:
    """Execute the stability test of the chosen plan: predicted folding free-energy change of the substitution.

    Args:
        test_id: ID (T...) of the chosen test candidate of kind stability_effect.
    """
    return _implementation(test_id=test_id)
