"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.experiments import run_ligand_contact_test as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def run_ligand_contact_test(test_id: str) -> str:
    """Execute the ligand contact test of the chosen plan: is the variant residue next to a ligand in experimental structures.

    Args:
        test_id: ID (T...) of the chosen test candidate of kind ligand_contact.
    """
    return _implementation(test_id=test_id)
