"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import search_literature as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def search_literature(gene: str, variant_id: str | None = None, query: str | None = None, limit: int = 6) -> str:
    """Search Europe PMC for publications on a gene, optionally narrowed to a variant or to free text.

    Args:
        gene: HGNC gene symbol.
        variant_id: Helix variant ID to narrow the search to papers naming the variant.
        query: Extra free-text terms, for example "PH domain inositol phosphate binding".
        limit: Number of publications to return, 1 to 10.
    """
    return _implementation(gene=gene, variant_id=variant_id, query=query, limit=limit)
