"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import search_entities as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def search_entities(query: str) -> str:
    """Resolve free text to Helix entities: disease, gene, protein, variant, structure or paper.

    Args:
        query: Text such as "BTK R28H", "XLA" or "Q06187".
    """
    return _implementation(query=query)
