"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_job_status as _implementation

context.set_role("runner")


@tool(strict=False)
def get_job_status(job_id: str) -> str:
    """Status, stages and manifest location of an OrphaFold computational job.

    Args:
        job_id: Job ID, starting with job_.
    """
    return _implementation(job_id=job_id)
