"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.experiments import run_structural_context_test as _implementation

context.set_role("runner")


@tool(strict=False)
def run_structural_context_test(test_id: str) -> str:
    """Execute the structural context test of the chosen plan: predicted pocket and interface membership of the residue.

    Args:
        test_id: ID (T...) of the chosen test candidate of kind structural_context.
    """
    return _implementation(test_id=test_id)
