"""Anonymous workspace identity.

The client generates an ID, keeps it in localStorage and sends it as X-OrphaFold-Workspace. The
server stores only its SHA-256 and creates the actor row on the first write. The actor ID is
separate from the workspace key, so an account can claim the actor later (actor.kind becomes
'account', an actor_identity row links the auth provider) without touching anything it owns.
"""

import re
from typing import Annotated

from fastapi import Depends, Header
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from orphafold.config import WORKSPACE_HEADER
from orphafold.db.models import Actor
from orphafold.db.session import get_session
from orphafold.errors import BadRequest, WorkspaceRequired
from orphafold.hashing import sha256_hex
from orphafold.ids import ACTOR_PREFIX, new_id, utcnow

WORKSPACE_ID_RE = re.compile(r"^[A-Za-z0-9_-]{16,128}$")

WorkspaceHeader = Annotated[
    str | None,
    Header(
        alias=WORKSPACE_HEADER,
        description="Anonymous workspace ID generated by the client: 16-128 characters of A-Z a-z 0-9 _ -",
    ),
]


def _workspace_key_hash(workspace_id: str) -> str:
    if not WORKSPACE_ID_RE.match(workspace_id):
        raise BadRequest(
            f"{WORKSPACE_HEADER} must be 16-128 characters of letters, digits, hyphen or underscore.",
            code="invalid_workspace_id",
        )
    return sha256_hex(workspace_id)


async def _find_actor(session: AsyncSession, key_hash: str) -> Actor | None:
    return await session.scalar(select(Actor).where(Actor.workspace_key_hash == key_hash))


async def get_optional_actor(
    workspace_id: WorkspaceHeader = None, session: AsyncSession = Depends(get_session)
) -> Actor | None:
    """Actor of the calling workspace if it exists. Never creates one: use it for reads."""
    if not workspace_id:
        return None
    return await _find_actor(session, _workspace_key_hash(workspace_id))


async def require_actor(
    workspace_id: WorkspaceHeader = None, session: AsyncSession = Depends(get_session)
) -> Actor:
    """Actor of the calling workspace, created on this first write. 400 without the header."""
    if not workspace_id:
        raise WorkspaceRequired(f"Send the {WORKSPACE_HEADER} header to save work or start jobs.")
    key_hash = _workspace_key_hash(workspace_id)
    actor = await _find_actor(session, key_hash)
    if actor is not None:
        actor.last_seen_at = utcnow()
        await session.commit()
        return actor
    actor = Actor(id=new_id(ACTOR_PREFIX), kind="anonymous", workspace_key_hash=key_hash)
    session.add(actor)
    try:
        await session.commit()
    except IntegrityError:
        # Two first writes raced: the other request created the actor
        await session.rollback()
        existing = await _find_actor(session, key_hash)
        if existing is None:
            raise
        return existing
    return actor


OptionalActor = Annotated[Actor | None, Depends(get_optional_actor)]
CurrentActor = Annotated[Actor, Depends(require_actor)]
