"""FastAPI application. Run: cd api && .venv/bin/uvicorn orphafold.main:app --port 8000"""

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic.json_schema import models_json_schema

from orphafold import __version__
from orphafold.artifacts.store import get_artifact_store
from orphafold.config import API_PREFIX, WORKSPACE_HEADER, Settings, get_settings
from orphafold.db.session import create_all, dispose_engine, init_engine
from orphafold.errors import install_error_handlers
from orphafold.jobs.manifest import RunManifest
from orphafold.jobs.queue import create_queue, set_queue
from orphafold.jobs.registry import all_handlers
from orphafold.jobs.service import recover_jobs
from orphafold.jobs.worker import Worker
from orphafold.knowledge.catalog import load_catalog
from orphafold.log import configure_logging, get_logger
from orphafold.plugins import load_plugins
from orphafold.providers.base import all_providers
from orphafold.routers import discover_routers
from orphafold.schemas.common import Evidence, Provenance, StructureDescriptor
from orphafold.schemas.jobs import StructureJobResult
from orphafold.sources.base import all_sources, close_http_clients, purge_http_cache

logger = get_logger(__name__)

SHARED_SCHEMAS = (Evidence, Provenance, StructureDescriptor, StructureJobResult, RunManifest)

DESCRIPTION = """\
Open research platform for computational rare-disease work. Research and hypothesis generation
only: nothing served here is clinical advice.

Every error is problem JSON (`application/problem+json`). Aggregated responses carry
`sources: SourceStatus[]`, so a page renders when one upstream source is down. Writes need the
`X-OrphaFold-Workspace` header (an anonymous ID generated by the client).
"""


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    settings: Settings = app.state.settings
    init_engine(settings)
    await create_all()
    load_catalog()
    get_artifact_store()

    queue = create_queue(settings)
    await queue.connect()
    set_queue(queue)

    worker: Worker | None = None
    if settings.runs_embedded_worker:
        in_process = queue.name == "memory"
        await recover_jobs(queue, all_running_are_orphaned=in_process)
        worker = Worker(queue, sweep=not in_process)
        await worker.start()
    app.state.worker = worker

    await purge_http_cache()
    # A first availability probe can take many seconds: start them now so no page waits for one
    app.state.provider_probes = (
        [asyncio.create_task(provider._checked_availability()) for provider in all_providers()]
        if settings.environment != "test"
        else []
    )
    logger.info(
        "OrphaFold API %s ready: %d sources, %d providers, %d job kinds, queue=%s",
        __version__,
        len(all_sources()),
        len(all_providers()),
        len(all_handlers()),
        queue.name,
    )
    try:
        yield
    finally:
        for probe in app.state.provider_probes:
            probe.cancel()
        if worker is not None:
            await worker.stop()
        await queue.close()
        set_queue(None)
        await close_http_clients()
        await dispose_engine()


def publish_shared_schemas(app: FastAPI) -> None:
    """Add the shared schemas to the OpenAPI components even while no route returns them, so
    generated client types always include Evidence, StructureDescriptor and the run manifest."""
    generate = app.openapi

    def openapi() -> dict[str, Any]:
        if app.openapi_schema:
            return app.openapi_schema
        document = generate()
        _, definitions = models_json_schema(
            [(model, "serialization") for model in SHARED_SCHEMAS],
            ref_template="#/components/schemas/{model}",
        )
        components = document.setdefault("components", {}).setdefault("schemas", {})
        for name, schema in definitions.get("$defs", {}).items():
            components.setdefault(name, schema)
        return document

    app.openapi = openapi  # type: ignore[method-assign]


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()
    configure_logging(settings.log_level, settings.log_format)
    load_plugins()

    app = FastAPI(
        title="OrphaFold API",
        version=__version__,
        description=DESCRIPTION,
        license_info={"name": "Apache-2.0", "identifier": "Apache-2.0"},
        lifespan=lifespan,
        openapi_url=f"{API_PREFIX}/openapi.json",
        docs_url=f"{API_PREFIX}/docs",
        redoc_url=None,
    )
    app.state.settings = settings
    app.state.worker = None
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_origin_regex=settings.resolved_cors_origin_regex,
        allow_methods=["*"],
        allow_headers=["*", WORKSPACE_HEADER, "Last-Event-ID"],
        expose_headers=["ETag", "Location", "Content-Disposition"],
        max_age=600,
    )
    install_error_handlers(app)
    for router in discover_routers():
        app.include_router(router, prefix=API_PREFIX)
    publish_shared_schemas(app)
    return app


app = create_app()
