"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_gene as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def get_gene(symbol: str) -> str:
    """Gene record: identifiers, the inborn errors of immunity it causes, and counts of variants and structures.

    Args:
        symbol: HGNC gene symbol, for example BTK.
    """
    return _implementation(symbol=symbol)
