"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_protein as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def get_protein(accession: str) -> str:
    """Protein entry from UniProtKB: function, domains with residue ranges, catalytic activity and locations.

    Args:
        accession: UniProt accession, for example Q06187.
    """
    return _implementation(accession=accession)
