"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_variant as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def get_variant(variant_id: str) -> str:
    """One variant: ClinVar classification, UniProtKB variant annotation, gnomAD frequency and predicted consequence.

    Args:
        variant_id: OrphaFold variant ID, for example BTK-p.Arg28His.
    """
    return _implementation(variant_id=variant_id)
