"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_evidence as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def record_evidence(statement: str, evidence_class: str, strength: str, database: str, record_id: str, url: str, refs: list[str] | None = None) -> str:
    """Record one piece of evidence with the database record it came from. Refused without a retrieved source.

    Args:
        statement: One factual sentence, as the source states it.
        evidence_class: experimental, clinical_database, literature, curated_database or computational_prediction.
        strength: The source's own strength or review level, as the tool returned it.
        database: Database name, copied from the tool output.
        record_id: Record ID in that database, copied exactly from the tool output.
        url: URL of the record, copied from the tool output.
        refs: IDs of related record items, for example the hypothesis or test this evidence bears on.
    """
    return _implementation(statement=statement, evidence_class=evidence_class, strength=strength, database=database, record_id=record_id, url=url, refs=refs)
