"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_handoff as _implementation

context.set_role("analysis")


@tool(strict=False)
def record_handoff(to: str, summary: str, refs: list[str] | None = None) -> str:
    """Record a handoff of work to another agent.

    Args:
        to: orchestrator, literature, knowledge_graph, insight, planner, safety, runner, analysis or human.
        summary: What is handed over and what the receiver must do or now knows. Two to four sentences.
        refs: IDs of the record items handed over (E..., G..., H..., T...).
    """
    return _implementation(to=to, summary=summary, refs=refs)
