"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_publication as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def get_publication(pmid: str) -> str:
    """One publication with its full abstract.

    Args:
        pmid: PubMed identifier.
    """
    return _implementation(pmid=pmid)
