"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.api import get_variant_effect_values as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def get_variant_effect_values(accession: str, position: int, alternate: str) -> str:
    """Pathogenicity and conservation predictions for one substitution: AlphaMissense, popEVE, EVE, conservation.

    Args:
        accession: UniProt accession.
        position: Residue position, UniProt numbering.
        alternate: One-letter code of the variant amino acid, for example H.
    """
    return _implementation(accession=accession, position=position, alternate=alternate)
