"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_test_candidate as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_test_candidate(test_kind: str, description: str, tests_hypotheses: list[str], expected_learning: float, expected_learning_reasoning: str, feasibility: float, feasibility_reasoning: str) -> str:
    """Record one candidate test. Cost and the approval requirement are filled in from the test catalogue.

    Args:
        test_kind: A test kind returned by list_available_tests.
        description: What the test would measure for this variant and which outcome supports or refutes which hypothesis.
        tests_hypotheses: Hypothesis IDs (H...) the test discriminates between.
        expected_learning: 0 to 1. How much the outcome is expected to change the ranking of the hypotheses.
        expected_learning_reasoning: Why, naming the outcomes that would move each hypothesis.
        feasibility: 0 to 1. How likely the test runs to completion with the data and providers available now.
        feasibility_reasoning: Why, using the availability that list_available_tests reported.
    """
    return _implementation(test_kind=test_kind, description=description, tests_hypotheses=tests_hypotheses, expected_learning=expected_learning, expected_learning_reasoning=expected_learning_reasoning, feasibility=feasibility, feasibility_reasoning=feasibility_reasoning)
