"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.discovery import get_target_structure as _implementation

context.set_role("translator")


@tool(strict=False)
def get_target_structure(accession: str) -> str:
    """Predicted pockets and available structures of a candidate target, so a structural bridge can cite records.

    Args:
        accession: UniProt accession of the candidate target, copied from a candidate's target block.
    """
    return _implementation(accession=accession)
