"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.discovery import list_candidate_targets as _implementation

context.set_role("translator")


@tool(strict=False)
def list_candidate_targets(gene: str | None = None, disease: str | None = None, variant: str | None = None, exclude_direct: bool = False) -> str:
    """What a drug could act on for this subject, and which known molecules act on it, with the direction check.

    Returns one row per candidate with its bridge kind, its direction check and the records it cites, plus the
    ruled-out rows and the sources that answered. The full response is stored in the run directory; name a
    candidate by its candidate_ref in every later tool call.

    Args:
        gene: HGNC symbol; defaults to the gene of this run's subject.
        disease: Catalogue slug of the disease, when the subject is a disease.
        variant: Helix variant ID, when the subject is a variant.
        exclude_direct: True drops every edge that links the subject disease straight to a molecule, so a
            candidate has to be recovered through a bridge. The response lists what was withheld.
    """
    return _implementation(gene=gene, disease=disease, variant=variant, exclude_direct=exclude_direct)
