"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.experiments import list_available_tests as _implementation

context.set_role("planner")


@tool(strict=False)
def list_available_tests() -> str:
    """List the tests the runner can execute for this run's variant, with what each measures, its cost, whether it needs human approval, and whether it can run right now.
    """
    return _implementation()
