"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import read_record as _implementation

context.set_role("planner")


@tool(strict=False)
def read_record(sections: list[str] | None = None) -> str:
    """Read the shared research record of this run as a compact digest.

    Args:
        sections: Parts to return. Any of evidence, gaps, hypotheses, tests, plans, safety, results,
            interpretations, decisions, next_experiments, notes. Omit to get all of them.
    """
    return _implementation(sections=sections)
