"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import record_plan as _implementation

context.set_role("planner")


@tool(strict=False)
def record_plan(chosen_test_id: str, rationale: str, rejected: list[dict[str, str]]) -> str:
    """Record the plan: the one test chosen among the open candidates and why every other one was rejected.

    Args:
        chosen_test_id: ID (T...) of the chosen test.
        rationale: Why this test, comparing expected learning, feasibility and cost against the remaining budget.
        rejected: One object per candidate that was not chosen, each with test_id and reason.
    """
    return _implementation(chosen_test_id=chosen_test_id, rationale=rationale, rejected=rejected)
