"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.budget import get_budget_status as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def get_budget_status() -> str:
    """Return the run budget: tool calls and compute seconds allowed, used and remaining.
    """
    return _implementation()
