"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import record_interpretation as _implementation

context.set_role("analysis")


@tool(strict=False)
def record_interpretation(test_id: str, per_hypothesis: list[dict[str, str]], uncertainty: str) -> str:
    """Record what the test result means for every hypothesis.

    Args:
        test_id: ID (T...) of the interpreted test.
        per_hypothesis: One object per hypothesis with id, verdict (supported, weakened, refuted or unchanged)
            and why, naming the measured value behind the verdict.
        uncertainty: What the result cannot show and how far the verdicts can be trusted.
    """
    return _implementation(test_id=test_id, per_hypothesis=per_hypothesis, uncertainty=uncertainty)
