"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import request_approval as _implementation

context.set_role("safety")


@tool(strict=False)
def request_approval(test_id: str, reason: str, risk: str) -> str:
    """Ask a human to approve a consequential test and wait for the decision. Returns approved or rejected.

    Args:
        test_id: ID (T...) of the chosen test that needs approval.
        reason: Why the lab wants to run it, in one or two sentences a scientist can judge.
        risk: What the action costs or touches: compute, external services, data leaving the lab.
    """
    return _implementation(test_id=test_id, reason=reason, risk=risk)
