"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.candidates import review_candidates as _implementation

context.set_role("safety")


@tool(strict=False)
def review_candidates() -> str:
    """Read the candidate proposal with each candidate's direction check, bridge steps and cited records, and which of them must be rejected.
    """
    return _implementation()
