"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.record import review_claims as _implementation

context.set_role("safety")


@tool(strict=False)
def review_claims() -> str:
    """Check every statement in the record for clinical or treatment wording, uncited evidence and unlabelled hypotheses, and report the chosen test's approval requirement.
    """
    return _implementation()
