"""Generate the Omnigent agent bundles from the registry.

Writes, for the supervisor, every specialist and the single-agent baseline: config.yaml, and one
tools/python/<tool>.py per permitted tool (Omnigent grants a local tool by file name). Also writes
lab/agents/agents.json, the agent specifications and policies as data for the API.

Prompts live in AGENTS.md next to each config.yaml and are written by hand.

    lab/.venv/bin/python lab/tools/generate_agent_tools.py
"""

import importlib
import inspect
import json
import shutil
import sys
from pathlib import Path
from typing import Any

LAB = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(LAB / "tools"))
sys.path.insert(0, str(LAB / "policies"))

from orphafold_lab_policies.policies import POLICY_REGISTRY  # noqa: E402
from orphafold_lab_tools import registry  # noqa: E402
from orphafold_lab_tools.catalogue import (  # noqa: E402
    CONSEQUENTIAL_TOOLS,
    EXPERIMENT_TOOLS,
    MECHANISM_CLASSES,
    TESTS,
)

LAB_BUNDLE = LAB / "agents" / "orphafold_lab"
BASELINE_BUNDLE = LAB / "agents" / "orphafold_baseline"
HARNESS = "claude-sdk"
HEADER = "# Generated by lab/tools/generate_agent_tools.py from orphafold_lab_tools/registry.py.\n# Change the registry or AGENTS.md, then run the generator again.\n"
POLICY_ORDER = ("role_boundary", "approval_gate", "claims_guard", "run_budget")
TOOL_TIMEOUTS = {"safety": 1000, "runner": 600}

WRAPPER = '''"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from {module} import {name} as _implementation

context.set_role("{role}")


@tool(strict=False)
def {name}{signature}:
    """{docstring}
    """
    return _implementation({arguments})
'''


def wrapper_source(name: str, role: str) -> str:
    """Source of one tool file: Omnigent only registers functions defined in the file itself."""
    module = registry.IMPLEMENTATIONS[name]
    function = getattr(importlib.import_module(module), name)
    signature = inspect.signature(function)
    docstring = (inspect.getdoc(function) or name).replace("\n", "\n    ").replace("    \n", "\n")
    arguments = ", ".join(f"{parameter}={parameter}" for parameter in signature.parameters)
    return WRAPPER.format(
        module=module,
        name=name,
        role=role,
        signature=str(signature),
        docstring=docstring,
        arguments=arguments,
    )


def tool_description(name: str) -> str:
    module = importlib.import_module(registry.IMPLEMENTATIONS[name])
    return (inspect.getdoc(getattr(module, name)) or "").split("\n\n")[0].replace("\n", " ")


def tool_kind(name: str) -> str:
    if name in EXPERIMENT_TOOLS:
        return "experiment"
    if name in registry.RETRIEVAL_TOOLS:
        return "retrieval"
    return "record"


def write_tools(directory: Path, tools: list[str], record_role: str) -> None:
    target = directory / "tools" / "python"
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    for name in tools:
        (target / f"{name}.py").write_text(wrapper_source(name, record_role), encoding="utf-8")


def policies_block(role: str) -> str:
    lines = ["guardrails:", "  policies:"]
    for name in POLICY_ORDER:
        lines += [
            f"    {name}:",
            "      type: function",
            "      function:",
            f"        path: orphafold_lab_policies.policies.{name}",
            "        arguments:",
            f"          role: {role}",
        ]
    return "\n".join(lines) + "\n"


def write_config(
    directory: Path,
    name: str,
    definition: dict[str, Any],
    policy_role: str,
    *,
    timeout: int,
    sub_agents: list[str] | None = None,
) -> None:
    lines = [
        HEADER.rstrip(),
        "spec_version: 1",
        f"name: {name}",
        "description: >-",
        f"  {definition['title']}. Owns: {definition['decision']}",
        "executor:",
        "  type: omnigent",
        f"  model: {definition['model']}",
        "  config:",
        f"    harness: {HARNESS}",
        "instructions: AGENTS.md",
        "# No host skills, settings or connectors: the declared tools are the whole capability of the agent",
        "skills: none",
        f"async: {'true' if sub_agents else 'false'}",
        "tools:",
        f"  timeout: {timeout}",
    ]
    if sub_agents:
        lines.append("  agents:")
        lines += [f"    - {agent}" for agent in sub_agents]
    (directory / "config.yaml").write_text(
        "\n".join(lines) + "\n" + policies_block(policy_role), encoding="utf-8"
    )


def agent_entry(
    identifier: str, definition: dict[str, Any], directory: Path, policy_role: str
) -> dict[str, Any]:
    prompt_path = directory / "AGENTS.md"
    return {
        "id": identifier,
        "title": definition["title"],
        "model": definition["model"],
        "harness": HARNESS,
        "decision": definition["decision"],
        "inputs": definition["inputs"],
        "output": definition["output"],
        "tools": [
            {
                "name": name,
                "kind": tool_kind(name),
                "requires_approval": name in CONSEQUENTIAL_TOOLS,
                "description": tool_description(name),
            }
            for name in definition["tools"]
        ],
        "orchestration_tools": definition.get("orchestration_tools", []),
        "policies": [f"{name}(role={policy_role})" for name in POLICY_ORDER],
        "spec_path": str((directory / "config.yaml").relative_to(LAB.parent)),
        "prompt_path": str(prompt_path.relative_to(LAB.parent)),
        "prompt": prompt_path.read_text(encoding="utf-8") if prompt_path.exists() else None,
    }


def main() -> None:
    specialists = list(registry.SPECIALISTS)
    LAB_BUNDLE.mkdir(parents=True, exist_ok=True)
    write_tools(LAB_BUNDLE, registry.SUPERVISOR["tools"], "orchestrator")
    write_config(
        LAB_BUNDLE, "orphafold_lab", registry.SUPERVISOR, "orchestrator", timeout=300, sub_agents=specialists
    )
    agents = [agent_entry("orchestrator", registry.SUPERVISOR, LAB_BUNDLE, "orchestrator")]
    for role in specialists:
        directory = LAB_BUNDLE / "agents" / role
        directory.mkdir(parents=True, exist_ok=True)
        definition = registry.SPECIALISTS[role]
        write_tools(directory, definition["tools"], role)
        write_config(directory, role, definition, role, timeout=TOOL_TIMEOUTS.get(role, 240))
        agents.append(agent_entry(role, definition, directory, role))
    BASELINE_BUNDLE.mkdir(parents=True, exist_ok=True)
    write_tools(BASELINE_BUNDLE, registry.BASELINE["tools"], "orchestrator")
    write_config(BASELINE_BUNDLE, "orphafold_baseline", registry.BASELINE, "generalist", timeout=1000)
    skill = LAB_BUNDLE / "skills" / "discovery-loop" / "SKILL.md"
    manifest = {
        "generated_from": "lab/tools/orphafold_lab_tools/registry.py",
        "orchestration": {
            "framework": "Omnigent",
            "harness": HARNESS,
            "bundle": str(LAB_BUNDLE.relative_to(LAB.parent)),
            "dispatch": "The supervisor dispatches sub-agents with sys_session_send and collects results with sys_read_inbox.",
            "skill_path": str(skill.relative_to(LAB.parent)),
            "skill": skill.read_text(encoding="utf-8") if skill.exists() else None,
        },
        "agents": agents,
        "baseline": agent_entry("generalist", registry.BASELINE, BASELINE_BUNDLE, "generalist"),
        "policies": [
            {
                "id": entry["handler"].rsplit(".", 1)[-1],
                "name": entry["name"],
                "handler": entry["handler"],
                "description": entry["description"],
                "phases": ["tool_call", "response"]
                if entry["handler"].endswith("claims_guard")
                else ["tool_call"],
            }
            for entry in POLICY_REGISTRY
        ],
        "approval": {
            "tools_requiring_human_approval": sorted(CONSEQUENTIAL_TOOLS),
            "how": "The safety agent records an approval_request; a human answers through POST /api/v1/lab/runs/{run_id}/approvals/{approval_id} or the launcher's --approve flag; the approval_gate policy denies the tool until an approved approval_decision is in the record.",
        },
        "tests": TESTS,
        "mechanism_classes": MECHANISM_CLASSES,
        "closing_tools": sorted(registry.CLOSING_TOOLS),
    }
    (LAB / "agents" / "agents.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {len(agents)} lab agents, the baseline and agents.json")


if __name__ == "__main__":
    main()
