"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_reopening as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_reopening(hypothesis_id: str, reason: str) -> str:
    """Record that a result reopened the earlier choice and the planning step is opened again.

    Args:
        hypothesis_id: ID (H...) of the hypothesis that was favoured before the test.
        reason: Which result reopened it (contradicted, displaced or test not completed) and what is reconsidered.
    """
    return _implementation(hypothesis_id=hypothesis_id, reason=reason)
