"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_final_report as _implementation

context.set_role("orchestrator")


@tool(strict=False)
def record_final_report(markdown: str) -> str:
    """Record the final research report of the run. Refused when it holds clinical wording or an uncited fact.

    Args:
        markdown: The report. Every sentence that names a database, a structure or a measured value must
            cite a record ID such as [E3] or [T1]. Hypotheses are called agent-generated hypotheses.
    """
    return _implementation(markdown=markdown)
