"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import get_residue_annotations as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def get_residue_annotations(accession: str, position: int) -> str:
    """Every UniProtKB and InterPro annotation covering one residue: domain, binding site, active site, region, secondary structure.

    Args:
        accession: UniProt accession.
        position: Residue position, UniProt numbering.
    """
    return _implementation(accession=accession, position=position)
