"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import get_structure_ledger as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def get_structure_ledger(accession: str, position: int) -> str:
    """Structures of a protein that observe one residue: experimental entries with method, resolution and ligands, and the predicted model.

    Args:
        accession: UniProt accession.
        position: Residue position, UniProt numbering.
    """
    return _implementation(accession=accession, position=position)
