"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.api import list_variants_near as _implementation

context.set_role("knowledge_graph")


@tool(strict=False)
def list_variants_near(gene: str, position: int, window: int = 5) -> str:
    """Disease substitutions reported at the residue and within a window around it.

    Args:
        gene: HGNC gene symbol.
        position: Residue position, UniProt numbering.
        window: Residues on each side to include, 0 to 15.
    """
    return _implementation(gene=gene, position=position, window=window)
