"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from helix_lab_tools import context
from helix_lab_tools.openalex import search_openalex as _implementation

context.set_role("literature")


@tool(strict=False)
def search_openalex(query: str, limit: int = 6) -> str:
    """Search OpenAlex for scholarly works, with citation counts and abstracts.

    Args:
        query: Free text, for example "Bruton tyrosine kinase PH domain R28 inositol phosphate binding".
        limit: Number of works to return, 1 to 8.
    """
    return _implementation(query=query, limit=limit)
