"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_hypothesis as _implementation

context.set_role("insight")


@tool(strict=False)
def record_hypothesis(statement: str, mechanism_class: str, supports: list[str], would_refute: str, starting_rank: int, rank_rationale: str) -> str:
    """Record one testable mechanism hypothesis. It is stored with the label "agent-generated hypothesis".

    Args:
        statement: The hypothesis in one or two sentences, phrased as a molecular mechanism.
        mechanism_class: One of stability_folding (the fold is destabilised), ligand_binding (contact with a
            small molecule, lipid head group, nucleotide, cofactor or metal is lost), catalytic_site,
            protein_interaction (contact with another protein chain is lost, a homodimer included),
            nucleic_acid_binding, domain_interface (contact between domains of the same chain is lost),
            other. Each hypothesis needs a different class.
        supports: Evidence IDs only (E...) from the record that motivate the hypothesis. Gap IDs do not belong here.
        would_refute: The observable result that would refute it.
        starting_rank: 1 for the hypothesis the starting evidence favours most, 2 for the next, and so on.
        rank_rationale: Why the starting evidence places it at that rank.
    """
    return _implementation(statement=statement, mechanism_class=mechanism_class, supports=supports, would_refute=would_refute, starting_rank=starting_rank, rank_rationale=rank_rationale)
