"""Generated by lab/tools/generate_agent_tools.py. Do not edit."""

from omnigent_client import tool

from orphafold_lab_tools import context
from orphafold_lab_tools.record import record_safety_review as _implementation

context.set_role("safety")


@tool(strict=False)
def record_safety_review(test_id: str, verdict: str, findings: str) -> str:
    """Record the safety review of the chosen test and of the claims in the record.

    Args:
        test_id: ID (T...) of the chosen test of the latest plan.
        verdict: cleared when the plan and the recorded claims pass, blocked otherwise.
        findings: What was checked and what was found, including any flagged statement by its seq number.
    """
    return _implementation(test_id=test_id, verdict=verdict, findings=findings)
